# Generated by Django 5.2.11 on 2026-02-11 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_key', models.CharField(max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('priority', models.PositiveSmallIntegerField()),
                ('base_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['priority'], name='source_priority_idx'), models.Index(fields=['is_active'], name='source_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('items_collected', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.source')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='runlog_status_idx'), models.Index(fields=['started_at'], name='runlog_started_at_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_job_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('experience_level', models.CharField(blank=True, max_length=100)),
                ('experience_max_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(max_length=500)),
                ('description_snippet', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('source_category_path', models.CharField(blank=True, max_length=500)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.duplicategroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.source')),
            ],
            options={
                'indexes': [models.Index(fields=['posting_date'], name='job_posting_date_idx'), models.Index(fields=['closing_date'], name='job_closing_date_idx'), models.Index(fields=['location'], name='job_location_idx'), models.Index(fields=['experience_max_years'], name='job_exp_years_idx'), models.Index(fields=['collected_at'], name='job_collected_at_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_job_id'), name='unique_source_job')],
            },
        ),
    ]
